server:
  port: 8080

spring:
  application:
    name: nerabbs-service-oss

  cloud:
    consul:
      host: consul
      port: 8500

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

grpc:
  server:
    security:
      enabled: false

minio:
  endpoint: "http://minio:9000"
  user: nerabbs
  password: nerabbs#strong_password@2023

nerabbs:
  oss:
    upload:
      allowed-file-mime-types:
        - image/jpeg
        - image/png
        - image/gif
        - image/bmp
        - image/webp
        - image/avif