server:
  port: 8080

spring:
  application:
    name: nerabbs-service-user-profile

  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://postgres:5432/nerabbs
    username: nerabbs
    password: nerabbs

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

  cloud:
    consul:
      host: consul
      post: 8500

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

grpc:
  client:
    nerabbs-service-oss:
      address: 'discovery:///nerabbs-service-oss'
      negotiationType: PLAINTEXT
    nerabbs-service-user:
      address: 'discovery:///nerabbs-service-user'
      negotiationType: PLAINTEXT