apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-webauthn
  namespace: nerabbs
  labels:
    app: service-webauthn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-webauthn
  template:
    metadata:
      name: service-webauthn
      labels:
        app: service-webauthn
    spec:
      containers:
        - name: service-webauthn
          image: hikarilan/nerabbs:service-webauthn
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: configmap
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: service-webauthn
  namespace: nerabbs
spec:
  selector:
    app: service-webauthn
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
