server:
  port: 8080

spring:
  application:
    name: nerabbs-service-search

  datasource:
    url: jdbc:postgresql://postgres:5432/nerabbs
    username: nerabbs
    password: nerabbs

  cloud:
    consul:
      host: consul
      port: 8500

grpc:
  server:
    security:
      enabled: false

meilisearch:
  endpoint: "http://meilisearch:7700"
  masterKey: nerabbs#strong_password@2023