server:
  port: 8080

spring:
  application:
    name: nerabbs-service-search

  data:
    redis:
      host: redis
      port: 6379
      timeout: 10s

  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://postgres:5432/nerabbs
    username: nerabbs
    password: nerabbs

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

  sql:
    init:
      mode: always

  cloud:
    consul:
      host: consul
      port: 8500

  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "never"
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
            classLoadHelper:
              class: org.quartz.simpl.CascadingClassLoadHelper
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_

grpc:
  server:
    security:
      enabled: false

meilisearch:
  endpoint: "http://meilisearch:7700"
  masterKey: nerabbs#strong_password@2023